app_camera/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from .views.create import CameraCreateView
from .views.delete import CameraDeleteView
from .views.update import CameraUpdateView
from .views.detail import CameraDetailView

app_name = 'app_camera'

urlpatterns = [
    path('delete/<int:pk>', CameraDeleteView.as_view(), name='camera_delete'),
    path('detail/<int:pk>', CameraDetailView.as_view(), name='camera_detail'),
    path('update/<int:pk>', CameraUpdateView.as_view(), name='camera_update'),
    path('create/', CameraCreateView.as_view(), name='camera_create'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from app_dashboard.views import dashboard
from .api import api
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', api.urls),
    path('settings/', include('app_camera.urls')),
    path('', dashboard, name='dashboard'),
    # TODO update list
    # path('settings/', include('app_event.urls')),
    # path('detect/', include('app_color.urls')),
    # path('detect/', include('app_line.urls')),
    # path('detect/', include('app_pattren.urls')),
    # path('detect/', include('app_text.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_dashboard/models.py
from django.db import models

# Create your models here.

app_dashboard/views.py
from django.shortcuts import render
from app_camera.models import CameraSetting

# Create your views here.
def dashboard(request):
    camera = CameraSetting.objects.all()
    if camera.count() == 0:
        is_exsist_camera = False
    else:
        is_exsist_camera = True
    context = {
        'camera' : camera,
        'is_exsist_camera' : is_exsist_camera,
    }
    return render(request=request, template_name='app_dashboard/dashboard.html', context=context)

app_dashboard/templates/app_dashboard/dashboard.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="container-fluid">
  <div class="row">

      
      {% for cam in camera %}
      <div class="col-md-3 mr-1">
        <div class="row border">
          <div class="col-md-12 m-1">
            <div class="row">
              <div class="col-md-12">
                <div class="d-flex justify-content-between border-bottom">
                  <h5 class="card-title mt-2 ml-2 mb-0 font-weight-bold">
                    <a href="{% url 'app_camera:camera_detail' cam.id %}">
                      {{cam.id}}번 카메라
                    </a>
                  </h5>
                  <p class="text-left text-danger m-1 ">
                    <i class="mdi mdi-camcorder" id="alive{{cam.id}}"></i>
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-12 m-1">
            <div class="card">
              <div calss="card-title">
                <div class="row">
                  <div class="col-md-4">
                    <p class="text-center m-1">높이</p>
                  </div>
                  <div class="col-md-6 mt-2">
                    <div class="progress">
                      <div class="progress-bar bg-primary" id="line{{cam.id}}" role="progressbar" style="width: 0%" aria-valuenow="0"
                        aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-12 m-1">
            <div class="card">
              <div calss="card-title">
                <div class="row">
                  <div class="col-md-4">
                    <p class="text-center m-1">색상</p>
                  </div>
                  <div class="col-md-6 mt-2">
                    <div class="progress">
                      <div class="progress-bar" id="blue{{cam.id}}" role="progressbar" style="width: 33%" aria-valuenow="33"
                        aria-valuemin="0" aria-valuemax="100"></div>
                      <div class="progress-bar bg-success" id="green{{cam.id}}" role="progressbar" style="width: 33%"
                        aria-valuenow="33" aria-valuemin="0" aria-valuemax="100"></div>
                      <div class="progress-bar bg-danger" id="red{{cam.id}}" role="progressbar" style="width: 33%"
                        aria-valuenow="33" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-12 m-1">
            <div class="card">
              <div calss="card-title">
                <div class="row">
                  <div class="col-md-4">
                    <p class="text-center m-1">문자</p>
                  </div>
                  <div class="col-md-6 mt-2">
                    <div class="progress">
                      <div class="progress-bar bg-primary" id="text{{cam.id}}" role="progressbar" style="width: 0%" aria-valuenow="0"
                        aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div> 
      {% endfor %}

      <div class="col-md-3 mr-1">
        <div class="row border">
          <a href="{% url 'app_camera:camera_create' %}">새로만들기</a> 
        </div>
      </div> 


  </div>
</div>  


{% endblock content %}

{% block javascripts %}

<script src="{% static 'js/jquery-ui.js' %}"></script>

<script type="text/javascript">
  function event_ping(){
    {% for cam in camera %}
      $.ajax({
        "url": "api/camera/ping/{{cam.id}}",
        "type": "get",
        "dataType": "json",
        "success": function (data) {
          if (data.ping){
            if ($("#alive{{cam.id}}").hasClass("mdi mdi-camcorder-off") == 1){
              $("#alive{{cam.id}}").removeClass("mdi mdi-camcorder-off").addClass("mdi mdi-camcorder");
            }
          }
          else{
            if ($("#alive{{cam.id}}").hasClass("mdi mdi-camcorder") == 1){
              $("#alive{{cam.id}}").removeClass("mdi mdi-camcorder").addClass("mdi mdi-camcorder-off");
            }
          }
        },
        "error": function (info, xhr) {
          if (info.readyState == '4') {
            //alert('문제가 발생했습니다.\n상태코드 : ' + info.status+ '\n\n' + info.responseText);
          } else {
            //alert('문제가 발생했습니다.\n잠시후 다시 시도해 주세요.\n 상태코드 : ' +info.status);
          }
        }
      });
    {% endfor %}
  }
  setInterval(event_ping, 10000);

  async function event_motion_text(id) {

    $.ajax({
      
      "url": "api/text/result/" + id,
      "type": "get",
      "dataType": "json",
      "success": function (data) {
        var len = data.text_rec.length;
        var len_rate = len / 3 * 100;

        $('#text' + id).attr('area-valuenow', len_rate).css('width', len_rate + '%');
      },
      "error": function (info, xhr) {
        if (info.readyState == '4') {
          //alert('문제가 발생했습니다.\n상태코드 : ' + info.status+ '\n\n' + info.responseText);
        } else {
          //alert('문제가 발생했습니다.\n잠시후 다시 시도해 주세요.\n 상태코드 : ' +info.status);
        }
      }
    });

  }

  async function event_motion_line(id) {
    $.ajax({
      
      "url": "api/line/result/" + id,
      "type": "get",
      "dataType": "json",
      "success": function (data) {
        $('#line' + id).attr('area-valuenow', data.LENGTH).css('width', data.LENGTH + '%');
      },
      "error": function (info, xhr) {
        if (info.readyState == '4') {
          //alert('문제가 발생했습니다.\n상태코드 : ' + info.status+ '\n\n' + info.responseText);
        } else {
          //alert('문제가 발생했습니다.\n잠시후 다시 시도해 주세요.\n 상태코드 : ' +info.status);
        }
      }
    });
  }

  async function event_motion_color(id) {
      $.ajax({
        
        "url": "api/color/result/" + id,
        "type": "get",
        "dataType": "json",
        "success": function (data) {
          if ((data.color.red > 0) & (data.color.red <= 3)) {
            $("#red" + id).show();
          }
          else{
            $("#red" + id).hide();
          }

          if (data.color.green > 0) {
            $("#green" + id).show();
          }
          else{
            $("#green" + id).hide();
          }

          if (data.color.blue > 0) {
            $("#blue" + id).show();
          }
          else{
            $("#blue" + id).hide();
          }
        },
        "error": function (info, xhr) {
          if (info.readyState == '4') {
            //alert('문제가 발생했습니다.\n상태코드 : ' + info.status+ '\n\n' + info.responseText);
          } else {
            //alert('문제가 발생했습니다.\n잠시후 다시 시도해 주세요.\n 상태코드 : ' +info.status);
          }
        }
      });
    }

  
    function getInterval(id){
    var get_data ;
    $.ajax({
      
      "url": "api/event/interval/" + id,
      "type": "get",
      "dataType": "json",
      "async": false,
      "success": function (data) {
        get_data = data;
      },
      "error": function (info, xhr) {
        if (info.readyState == '4') {
          //alert('문제가 발생했습니다.\n상태코드 : ' + info.status+ '\n\n' + info.responseText);
        } else {
          //alert('문제가 발생했습니다.\n잠시후 다시 시도해 주세요.\n 상태코드 : ' +info.status);
        }
      }
    });
    return get_data;
  }

  function interval(){
    {% for cam in camera %}
    var id = {{cam.id}};
    var get_data = getInterval(id);
    console.log(get_data);
    var interval_time_text = get_data.text_interval;
    setInterval(event_motion_text, interval_time_text * 1000, id);
    var interval_time_line = get_data.line_interval;
    setInterval(event_motion_line, interval_time_line * 1000, id);
    var interval_time_color = get_data.color_interval;
    setInterval(event_motion_color, interval_time_color * 1000, id);
    {% endfor %}
  }
  
  interval();

</script>

<script type="text/javascript">

</script>


{% endblock javascripts %}