app_camera/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from .views.create import CameraCreateView
from .views.delete import CameraDeleteView
from .views.update import CameraUpdateView
from .views.detail import CameraDetailView

app_name = 'app_camera'

urlpatterns = [
    path('delete/<int:pk>', CameraDeleteView.as_view(), name='camera_delete'),
    path('detail/<int:pk>', CameraDetailView.as_view(), name='camera_detail'),
    path('update/<int:pk>', CameraUpdateView.as_view(), name='camera_update'),
    path('create/', CameraCreateView.as_view(), name='camera_create'),
]

app_event/urls.py
from django.contrib import admin
from django.urls import path

from .views.update.interval import IntervalUpdateView
from .views.update.text import TextROIControlUpdateView
from .views.update.line import LineROIControlUpdateView

app_name = 'app_event'

urlpatterns = [
    path('interval/<int:camera_id>', IntervalUpdateView.as_view(), name='event_interval'),
    path('text/<int:camera_id>', TextROIControlUpdateView.as_view(), name='event_text'),
    path('line/<int:camera_id>', LineROIControlUpdateView.as_view(), name='event_line'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from app_dashboard.views import dashboard
from .api import api
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', api.urls),
    path('settings/', include('app_camera.urls')),
    path('', dashboard, name='dashboard'),
    # TODO update list
    # path('settings/', include('app_event.urls')),
    # path('detect/', include('app_color.urls')),
    # path('detect/', include('app_line.urls')),
    # path('detect/', include('app_pattren.urls')),
    # path('detect/', include('app_text.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_camera/models.py
from django.db import models

# Create your models here.
class CameraSetting(models.Model):
    id           = models.AutoField(primary_key=True)
    camera_name  = models.TextField(default='', max_length=255, verbose_name='카메라 이름')
    camera_id    = models.TextField(default='', max_length=255, verbose_name='카메라 아이디')
    camera_pw    = models.TextField(default='', max_length=255, verbose_name='카메라 비밀번호')
    camera_ip    = models.TextField(max_length=255, verbose_name='카메라 아이피')
    camera_port  = models.TextField(default='', max_length=255, verbose_name='카메라 포트')
    camera_url   = models.TextField(default='', max_length=255, verbose_name='RTSP URL')
    camera_alive = models.BooleanField(default=False)
    
    def __str__(self):
        if self.camera_port == '':
            return f'rtsp://{self.camera_id}:{self.camera_pw}@{self.camera_ip}/{self.camera_url}'
        
        elif self.camera_id == '' or self.camera_pw == '':
            return f'rtsp://{self.camera_ip}:{self.camera_port}/{self.camera_url}'
        
        elif self.camera_port == '' and (self.camera_id == '' or self.camera_pw == ''):
            return f'rtsp://{self.camera_ip}/{self.camera_url}'
        
        return f'rtsp://{self.camera_id}:{self.camera_pw}@{self.camera_ip}:{self.camera_port}/{self.camera_url}'

class CameraCapture(models.Model):
    camera         = models.ForeignKey('app_camera.CameraSetting', on_delete=models.CASCADE, verbose_name='카메라 아이디')
    camera_capture = models.ImageField(null=True, verbose_name='카메라 캡쳐', upload_to='capture/')

app_camera/views/forms.py
from django import forms
from ..models import CameraSetting

class CameraForm(forms.ModelForm):
    camera_name     = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    camera_id       = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    camera_pw       = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    camera_ip       = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    camera_port     = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    camera_url      = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = CameraSetting
        fields = ['camera_name', 'camera_id', 'camera_pw', 'camera_ip', 'camera_port', 'camera_url', ]

app_camera/views/create.py
from django.views.generic import CreateView
from django.shortcuts import resolve_url

class CameraCreateView(CreateView):
    from ..models import CameraSetting
    from .forms import CameraForm

    model = CameraSetting
    context_object_name = 'camera'
    form_class = CameraForm
    template_name = 'app_camera/camera_form.html'

    def get_success_url(self):
        return resolve_url('dashboard')

    def get_context_data(self, **kwargs):
        context = super(CameraCreateView, self).get_context_data(**kwargs)
        context['info'] = '카메라 정보를 새로 등록합니다.'

        return context

app_camera/views/delete.py
from django.views.generic import View
from django.shortcuts import resolve_url

class CameraDeleteView(View):
    def get(self, request, pk):
        from ..models import CameraSetting
        camera = CameraSetting.objects
        get_camera = camera.filter(id=pk)
        get_camera.delete()
        
        return resolve_url('dashboard')

app_camera/views/detail.py
from django.views.generic import DetailView
from django.shortcuts import get_object_or_404
from ..models import CameraSetting, CameraCapture
from app_event.models import IntervalControl, ColorROIControl, LineROIControl, TextROIControl

class CameraDetailView(DetailView):
    model = CameraSetting
    context_object_name = 'camera'
    template_name = 'app_camera/detail.html'

    def get(self, request, *args, **kwargs):
        from ..api import get_frame
        json = get_frame(request, self.kwargs['pk'])
        return super().get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super(CameraDetailView, self).get_context_data(**kwargs)
        context['media'] = get_object_or_404(CameraCapture, pk=self.kwargs['pk'])
        # context['color_roi'] = get_object_or_404(ColorROIControl, pk=self.kwargs['pk'])
        # context['line_roi'] = get_object_or_404(LineROIControl, pk=self.kwargs['pk'])
        # context['text_roi'] = get_object_or_404(TextROIControl, pk=self.kwargs['pk'])
        # context['interval'] = get_object_or_404(IntervalControl, pk=self.kwargs['pk'])
        return context

app_camera/views/update.py
from django.views.generic import UpdateView
from django.shortcuts import resolve_url

class CameraUpdateView(UpdateView):
    from ..models import CameraSetting
    from .forms import CameraForm
    model = CameraSetting
    context_object_name = 'camera'
    form_class = CameraForm
    template_name = 'app_camera/form.html'
    
    def get_success_url(self):
        return resolve_url('app_camera:camera_detail', self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(CameraUpdateView, self).get_context_data(**kwargs)
        context['info'] = '카메라 정보를 수정 합니다.'

        return context

app_camera/templates/app_camera/camera_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row">
    <div class="col-md-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">카메라 정보</h4>
                <p class="card-description">
                    {{ info }}
                </p>
                <form class="forms-sample" method="POST">
                    {% csrf_token %}
                    {% if form.errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for field in form %}
                            {% if field.errors %}
                                <strong>{{ field.label }}</strong>
                                {{ field.errors }}
                            {% endif %}
                        {% endfor %}
                    </div>
                    {% endif %}
                    {% for field in form.hidden_fields %}
                    {{field}}
                    {% endfor %}
                    {% for field in form.visible_fields %}
                    <div class="form-group">
                        {{field.errors}}
                        {{field.label_tag}}{{field}}
                    </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button class="btn btn-light">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascripts %}
{% endblock javascripts %}

app_camera/templates/app_camera/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="row border-bottom">
    <div class="col-md-12">
         <div class="d-flex justify-content-between">
             <h2 class="text-left">cam-{{camera.camera_name}}</h2>
             <button type="button" class="btn btn-inverse-danger ftm-fw mb-1">삭제</button>
         </div>
    </div>
</div>

<div class="row">
    <div class="col-md-5">
        <div class="row mt-1">
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <p class="card-title mt-2 mb-0">카메라 정보</p>
                            <button type="button" class="btn btn-inverse-info btn-sm ftm-fw m-1" onclick="location.href='{% url 'app_camera:camera_update' camera.id %}'">수정</button>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>IP</th>
                                        <th>PORT</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th>{{camera.camera_ip}}</th>
                                        <th>{{camera.camera_port}}</th>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <p class="card-title mt-2 mb-0">이벤트 정보</p>
                            <button class="btn btn-inverse-info btn-sm mb-2" onclick="location.href='{% url 'app_event:event_interval' camera.id %}'">수정</button>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>감지</th>
                                        <th>시간</th>
                                        <th>결과</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th>선</th>
                                        <th id="interval_line"></th>
                                        <th><label class="badge badge-info m-0">'</label></th>
                                    </tr>
                                    <tr>
                                        <th>색상</th>
                                        <th id="interval_color"></th>
                                        <th><label class="badge badge-info m-0">'</label></th>
                                    </tr>
                                    <tr>
                                        <th>문자</th>
                                        <th id="interval_text"></th>
                                        <th><label class="badge badge-info m-0">'</label></th>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    <div class="col-md-7">
        <div class="row mt-1">
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <p class="card-title mt-2 mb-0">화면 영역 정보</p>
                            <div class="btn-group mb-2" role="group">
                                <button class="btn btn-outline-secondary btn-sm" id="color_form">선</button>
                                <button class="btn btn-outline-secondary btn-sm" id="line_form">색상</button>
                                <button class="btn btn-outline-secondary btn-sm" id="text_form">문자</button>
                            </div>
                            <button class="btn btn-inverse-info btn-sm mb-2" id="roi">수정</button>
                        </div>
                        <img src="{{media.camera_capture}}" class="img-fluid" alt="roi">
                        <div class="table table-hover">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>좌표</th>
                                        <th>너비</th>
                                        <th>높이</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th id="roi_xy">(,)</th>
                                        <th id="roi_w"></th>
                                        <th id="roi_h"></th>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block javascripts %}
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script type="text/javascript">    
    console.log("'start'");
    $(function(){
        
        $.ajax({
            "url": "{% url 'api-1.0.0:interval' camera.id %}",
            "type": "get",
            "dataType": "json",
            "success": function (data) {
                var line = data.line_interval;
                var color = data.color_interval;
                var text = data.text_interval;
                
                $("#interval_line").text(line + "초");
                $("#interval_color").text(color + "초");
                $("#interval_text").text(text + "초");
                
              },
              "error": function (info, xhr) {
                if (info.readyState == '4') {
                  //alert('문제가 발생했습니다.\n상태코드 : ' + info.status+ '\n\n' + info.responseText);
                } else {
                  //alert('문제가 발생했습니다.\n잠시후 다시 시도해 주세요.\n 상태코드 : ' +info.status);
                }
              }
        });
    });
    $("#color_form").click(function(){
        $.ajax({
            "url": "{% url 'api-1.0.0:color_roi' camera.id 'red' %}",
            "type": "get",
            "dataType": "json",
            "success": function (data) {
                var x = data.color_x;
                var y = data.color_y;
                var w = data.color_w;
                var h = data.color_h;
                change_text(x,y,w,h);
              },
              "error": function (info, xhr) {
                if (info.readyState == '4') {
                  //alert('문제가 발생했습니다.\n상태코드 : ' + info.status+ '\n\n' + info.responseText);
                } else {
                  //alert('문제가 발생했습니다.\n잠시후 다시 시도해 주세요.\n 상태코드 : ' +info.status);
                }
              }
        });
        $(this).data('clicked', true);
        $("#line_form").data('clicked', false);
        $("#text_form").data('clicked', false);
        
    });
    $("#line_form").click(function(){
        $.ajax({
            "url": "{% url 'api-1.0.0:line_roi' camera.id %}",
            "type": "get",
            "dataType": "json",
            "success": function (data) {
                var x = data.line_x;
                var y = data.line_y;
                var w = data.line_w;
                var h = data.line_h;
                change_text(x,y,w,h);
              },
              "error": function (info, xhr) {
                if (info.readyState == '4') {
                  //alert('문제가 발생했습니다.\n상태코드 : ' + info.status+ '\n\n' + info.responseText);
                } else {
                  //alert('문제가 발생했습니다.\n잠시후 다시 시도해 주세요.\n 상태코드 : ' +info.status);
                }
              }
        });
        $(this).data('clicked', true);
        $("#color_form").data('clicked', false);
        $("#text_form").data('clicked', false);
    });
    $("#text_form").click(function(){
        $.ajax({
            "url": "{% url 'api-1.0.0:text_roi' camera.id %}",
            "type": "get",
            "dataType": "json",
            "success": function (data) {
                var x = data.text_x;
                var y = data.text_y;
                var w = data.text_w;
                var h = data.text_h;
                change_text(x,y,w,h);
              },
              "error": function (info, xhr) {
                if (info.readyState == '4') {
                  //alert('문제가 발생했습니다.\n상태코드 : ' + info.status+ '\n\n' + info.responseText);
                } else {
                  //alert('문제가 발생했습니다.\n잠시후 다시 시도해 주세요.\n 상태코드 : ' +info.status);
                }
              }
        });
        $(this).data('clicked', true);
        $("#color_form").data('clicked', false);
        $("#line_form").data('clicked', false);
    });

        $("#roi").click(function(){
        if ($("#color_form").data('clicked')) {
            {% comment %} location.href = "{% url 'app_event:event_color' camera.id %}";  {% endcomment %}
        }
        else if ($("#line_form").data('clicked')) {
            {% comment %} location.href = "{% url 'app_event:event_line' camera.id %}";  {% endcomment %}
        }
        else if ($("#text_form").data('clicked')) {
            location.href = "{% url 'app_event:event_text' camera.id %}";
        } else {

        }
    });

    function change_text(x, y, w, h){
        $("#roi_xy").text("("+ x + "," + y + ")");
        $("#roi_w").text(w);
        $("#roi_h").text(h);
    }
</script>

{% endblock javascripts %}

app_camera/templates/app_camera/form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row">
    <div class="col-md-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">카메라 정보</h4>
                <p class="card-description">
                    {{ info }}
                </p>
                <form class="forms-sample" method="POST">
                    {% csrf_token %}
                    {% if form.errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for field in form %}
                            {% if field.errors %}
                                <strong>{{ field.label }}</strong>
                                {{ field.errors }}
                            {% endif %}
                        {% endfor %}
                    </div>
                    {% endif %}
                    {% for field in form.hidden_fields %}
                    {{field}}
                    {% endfor %}
                    {% for field in form.visible_fields %}
                    <div class="form-group">
                        {{field.errors}}
                        {{field.label_tag}}{{field}}
                    </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button class="btn btn-light">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascripts %}
{% endblock javascripts %}